# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('calendario', '0002_auto_20160311_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento_id', models.PositiveIntegerField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('elemento_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='calendario.Nodo')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='encuentrointernacional',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='evento',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='foro',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='panel',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='seminario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='level',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='level',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='level',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='level',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
