# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_auto_20160229_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='panel',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='seminario',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
