# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendario', '0003_auto_20160301_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padre_id', models.PositiveIntegerField()),
                ('hijo_id', models.PositiveIntegerField()),
                ('hijo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendario_relacion_as_hijo', to='contenttypes.ContentType')),
                ('padre_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendario_relacion_as_padre', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Responsables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_id', models.PositiveIntegerField()),
                ('actividad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='foro',
            name='padre_id',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='padre_type',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='padre_id',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='padre_type',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='padre_id',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='padre_type',
        ),
        migrations.AddField(
            model_name='foro',
            name='relacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='calendario.Relacion'),
        ),
        migrations.AddField(
            model_name='panel',
            name='relacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='calendario.Relacion'),
        ),
        migrations.AddField(
            model_name='seminario',
            name='relacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='calendario.Relacion'),
        ),
    ]
