# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_auto_20160312_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foro',
            name='tipo',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panel',
            name='tipo',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminario',
            name='tipo',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
