# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_auto_20160312_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='tipo',
        ),
    ]
