# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_auto_20160312_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodo',
            old_name='elemento_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='nodo',
            old_name='elemento_type',
            new_name='object_type',
        ),
    ]
