# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0006_auto_20160312_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodo',
            old_name='object_id',
            new_name='content_id',
        ),
        migrations.RenameField(
            model_name='nodo',
            old_name='object_type',
            new_name='content_type',
        ),
    ]
