# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_auto_20160409_1604'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.TextField()),
                ('pais', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('encuentro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.Encuentro')),
            ],
        ),
    ]
