# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='pais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usuarios.Pais'),
        ),
    ]
