# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_persona_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido_paterno',
            field=models.CharField(default='pendiente', max_length=100, verbose_name='apellido paterno'),
            preserve_default=False,
        ),
    ]
