# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_persona_apellido_materno'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='grado',
            field=models.IntegerField(choices=[(1, 'Dr'), (2, 'Dra'), (3, 'Mtro'), (4, 'Mtra'), (5, 'Lic'), (6, '')], default=6),
        ),
    ]
