# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_persona_grado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='es_coordinador',
        ),
    ]
