# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20160502_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nombre_corto', models.CharField(default='', max_length=150)),
                ('pais', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usuarios.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=300)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Institucion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Persona')),
            ],
        ),
    ]
