# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_auto_20160328_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.Espacio'),
        ),
        migrations.AddField(
            model_name='foro',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.Espacio'),
        ),
        migrations.AddField(
            model_name='panel',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.Espacio'),
        ),
        migrations.AddField(
            model_name='seminario',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.Espacio'),
        ),
    ]
