# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_auto_20160329_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuentro',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='calId',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='espacio',
        ),
    ]
