# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_panel_espacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='encuentro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actividades.Encuentro'),
            preserve_default=False,
        ),
    ]
