# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actividades', '0009_espacio_encuentro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('anotaciones', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.Espacio')),
                ('responsables', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reuniones',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('anotaciones', models.TextField(blank=True)),
                ('responsables', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'sesiones',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('anotaciones', models.TextField(blank=True)),
                ('responsables', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'talleres',
            },
        ),
        migrations.AddField(
            model_name='encuentro',
            name='anotaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foro',
            name='anotaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='anotaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seminario',
            name='anotaciones',
            field=models.TextField(blank=True),
        ),
    ]
