# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_auto_20160404_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.Espacio'),
        ),
        migrations.AddField(
            model_name='taller',
            name='fecha_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 4, 18, 40, 42, 993696, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
