# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_auto_20160404_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 7, 21, 46, 44, 199078, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuentro',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 7, 21, 46, 48, 915899, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foro',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 7, 21, 46, 51, 879890, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foro',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 7, 21, 46, 53, 784632, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panel',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 7, 21, 46, 56, 991644, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panel',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 7, 21, 46, 59, 159019, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reunion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 7, 21, 47, 1, 344908, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reunion',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 7, 21, 47, 6, 334667, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 7, 21, 47, 10, 972969, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminario',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 7, 21, 47, 13, 281838, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 7, 21, 47, 14, 863559, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 7, 21, 47, 16, 293741, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 7, 21, 47, 17, 700531, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 7, 21, 47, 19, 110710, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
