# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='participante',
            name='encuentro',
        ),
        migrations.RemoveField(
            model_name='reunion',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='reunion',
            name='responsables',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='responsables',
        ),
        migrations.AlterModelOptions(
            name='encuentro',
            options={'ordering': ['fecha_creacion', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='foro',
            options={'ordering': ['fecha_creacion', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='seminario',
            options={'ordering': ['fecha_creacion', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='panel',
            name='coordinador',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='intervienen',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='moderador',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='encuentro',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='panel',
            name='duracion',
            field=models.PositiveSmallIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminario',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='taller',
            name='duracion',
            field=models.PositiveSmallIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foro',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
        migrations.DeleteModel(
            name='Reunion',
        ),
        migrations.DeleteModel(
            name='Sesion',
        ),
    ]
