# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='responsables',
            field=models.ManyToManyField(blank=True, to='usuarios.Persona'),
        ),
        migrations.AlterField(
            model_name='foro',
            name='responsables',
            field=models.ManyToManyField(blank=True, to='usuarios.Persona'),
        ),
        migrations.AlterField(
            model_name='otraactividadseminario',
            name='responsables',
            field=models.ManyToManyField(blank=True, to='usuarios.Persona'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='responsables',
            field=models.ManyToManyField(blank=True, to='usuarios.Persona'),
        ),
        migrations.AlterField(
            model_name='presentacionponencia',
            name='responsables',
            field=models.ManyToManyField(blank=True, to='usuarios.Persona'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='responsables',
            field=models.ManyToManyField(blank=True, to='usuarios.Persona'),
        ),
        migrations.AlterField(
            model_name='seminario',
            name='responsables',
            field=models.ManyToManyField(blank=True, to='usuarios.Persona'),
        ),
        migrations.AlterField(
            model_name='sesionespecial',
            name='responsables',
            field=models.ManyToManyField(blank=True, to='usuarios.Persona'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='responsables',
            field=models.ManyToManyField(blank=True, to='usuarios.Persona'),
        ),
    ]
