# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20160420_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Encuentro')),
            ],
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='encuentro',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='espacio',
        ),
        migrations.AlterField(
            model_name='espacio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='espacio',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.Sede'),
        ),
    ]
