# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20160426_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.Espacio'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
