# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_auto_20160421_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actividades.Sede'),
            preserve_default=False,
        ),
    ]
